# Generated by Django 5.1.4 on 2025-01-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_jobpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='client',
            new_name='author',
        ),
    ]
